# Generated by Django 3.0.1 on 2020-01-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Postid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
