# Generated by Django 3.0.1 on 2020-01-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carcustomizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Customerlist',
        ),
    ]
