# Generated by Django 3.0.1 on 2020-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carcustomizations', '0002_auto_20200116_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlist',
            name='images',
            field=models.ImageField(default='', upload_to='Carcustomization/image'),
        ),
        migrations.AlterField(
            model_name='customerlist',
            name='address',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='customerlist',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='customerlist',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
