# Generated by Django 3.0.1 on 2020-01-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carcustomizations', '0003_auto_20200116_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
