# Generated by Django 3.0.1 on 2020-01-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carcustomizations', '0004_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
